# Generated by Django 3.1.7 on 2021-03-09 09:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_auto_20210308_2220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                allow_unicode=True, editable=True, populate_from="name", unique=True
            ),
        ),
    ]
